### ISSUE TITLE
Rename a node is changing workflow

### ISSUE THREAD

**Issue by louisvandiere** [alien4cloud/alien4cloud#38] opened 2014-11-26 16:29 UTC
I have 2 compute nodes with 2 services connected by a relationship.
When I rename my compute node (with the relationship source), the worflow is changing, and the service is hosted by the second compute.

Wanted topology and workflow:
![topology_1](https://cloud.githubusercontent.com/assets/9881297/5204625/2fe772a2-7591-11e4-8a2d-ef427e40b7c3.jpg)
![workflow_1](https://cloud.githubusercontent.com/assets/9881297/5204638/48a052dc-7591-11e4-80d2-031fe8075caf.jpg)

Topology and workflow after rename:
![topology_2](https://cloud.githubusercontent.com/assets/9881297/5204649/5cef56f2-7591-11e4-9133-56096c965979.jpg)
![worflow_2](https://cloud.githubusercontent.com/assets/9881297/5204654/6282bfbe-7591-11e4-84ef-09daf57dd552.jpg)

We clearly see that the service named arr is not hosted on ARR_rename.

Best regards.

**Comment by lucboutier** [comment] 2015-01-05 12:00
Renaming a node doesn't change the workflow but the issue is that Alien 4 Cloud doesn't currently prevent a single node to have multiple hosted_on relationships while a node must have only a single hosted_on target.

**Comment by PierreLemordant** [comment] 2015-02-02 14:12
Hi,

Does this answer your question?
Can we close this ticket ?

Pierre

**Closed** 2015-08-05 07:35 UTC
Labels: bug
